version: "3.8"

services:
  mysql-db:
    image: mysql:5.7
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}

  crm-app:
    build: .
    restart: on-failure
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql-db:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?useSSL=false&useUnicode=true&characterEncoding=utf8",
        "spring.datasource.username": "${MYSQLDB_USER}",
        "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.show-sql": "true",
        "spring.jackson.generate-ddl": "true",
        "spring.jpa.hibernate.ddl-auto": "create",
        "server.servlet.context-path": "/api",
        "springdoc.swagger-ui.path": "/swagger-ui.html"
      }'
    depends_on:
      - mysql-db