version: "3.8"

services:
  mysql-db:
    image: mysql:8.1.0
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    volumes:
      - db:/var/lib/mysql

#  crm-service:
#    build: .
#    restart: on-failure
#    ports:
#      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
#    env_file:
#      - .env
#    environment:
#      - spring_application_name=crm-service
#      - spring_datasource_driver-class-name=com.mysql.cj.jdbc.Driver
#      - server_port=${SPRING_DOCKER_PORT}
#      - spring_datasource_url=jdbc:mysql://mysql-db:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8
#      - spring_datasource_username=${MYSQLDB_USER}
#      - spring_datasource_password=${MYSQLDB_ROOT_PASSWORD}
#      - spring_jpa_show-sql=true
#      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#      - spring_jackson_generate-ddl=true
#      - spring_jpa_hibernate_ddl-auto=create
#      - server_servlet_context-path=/crm
#      - springdoc_swagger-ui_path=/docs
#
#      - eureka_instance_hostname=localhost
#      - eureka_client_service-url_default-zone=http://localhost:8761/eureka
#    depends_on:
#      - mysql-db
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true

volumes:
    db: